/*
 * SmartOTP SDK
 * SmartOTP API Specs for Payment
 *
 * OpenAPI spec version: 1.0.0
 * Contact: phuthinh@vnpt.vn
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.32
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SmartOtpSdk) {
      root.SmartOtpSdk = {};
    }
    root.SmartOtpSdk.RegisterOtpRequestModel = factory(root.SmartOtpSdk.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The RegisterOtpRequestModel model module.
   * @module model/RegisterOtpRequestModel
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RegisterOtpRequestModel</code>.
   * @alias module:model/RegisterOtpRequestModel
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>RegisterOtpRequestModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RegisterOtpRequestModel} obj Optional instance to populate.
   * @return {module:model/RegisterOtpRequestModel} The populated <code>RegisterOtpRequestModel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('activationCode'))
        obj.activationCode = ApiClient.convertToType(data['activationCode'], 'String');
      if (data.hasOwnProperty('transId'))
        obj.transId = ApiClient.convertToType(data['transId'], 'Number');
      if (data.hasOwnProperty('pin'))
        obj.pin = ApiClient.convertToType(data['pin'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} activationCode
   */
  exports.prototype.activationCode = undefined;

  /**
   * Transaction ID
   * @member {Number} transId
   */
  exports.prototype.transId = undefined;

  /**
   * @member {String} pin
   */
  exports.prototype.pin = undefined;


  return exports;

}));
