/*
 * SmartOTP SDK
 * SmartOTP API Specs for Payment
 *
 * OpenAPI spec version: 1.0.0
 * Contact: phuthinh@vnpt.vn
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.32
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SmartOtpSdk) {
      root.SmartOtpSdk = {};
    }
    root.SmartOtpSdk.RegisterOtpResponseModelData = factory(root.SmartOtpSdk.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The RegisterOtpResponseModelData model module.
   * @module model/RegisterOtpResponseModelData
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RegisterOtpResponseModelData</code>.
   * @alias module:model/RegisterOtpResponseModelData
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>RegisterOtpResponseModelData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RegisterOtpResponseModelData} obj Optional instance to populate.
   * @return {module:model/RegisterOtpResponseModelData} The populated <code>RegisterOtpResponseModelData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'Number');
      if (data.hasOwnProperty('appId'))
        obj.appId = ApiClient.convertToType(data['appId'], 'Number');
      if (data.hasOwnProperty('deviceId'))
        obj.deviceId = ApiClient.convertToType(data['deviceId'], 'Number');
      if (data.hasOwnProperty('qrCode'))
        obj.qrCode = ApiClient.convertToType(data['qrCode'], 'String');
      if (data.hasOwnProperty('secretKey'))
        obj.secretKey = ApiClient.convertToType(data['secretKey'], 'String');
    }
    return obj;
  }

  /**
   * @member {Number} userId
   */
  exports.prototype.userId = undefined;

  /**
   * @member {Number} appId
   */
  exports.prototype.appId = undefined;

  /**
   * @member {Number} deviceId
   */
  exports.prototype.deviceId = undefined;

  /**
   * @member {String} qrCode
   */
  exports.prototype.qrCode = undefined;

  /**
   * @member {String} secretKey
   */
  exports.prototype.secretKey = undefined;


  return exports;

}));
