/*
 * SmartOTP SDK
 * SmartOTP API Specs for Payment
 *
 * OpenAPI spec version: 1.0.0
 * Contact: phuthinh@vnpt.vn
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.32
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RegisterOtpResponseModelData'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RegisterOtpResponseModelData'));
  } else {
    // Browser globals (root is window)
    if (!root.SmartOtpSdk) {
      root.SmartOtpSdk = {};
    }
    root.SmartOtpSdk.RegisterOtpResponseModel = factory(root.SmartOtpSdk.ApiClient, root.SmartOtpSdk.RegisterOtpResponseModelData);
  }
}(this, function(ApiClient, RegisterOtpResponseModelData) {
  'use strict';

  /**
   * The RegisterOtpResponseModel model module.
   * @module model/RegisterOtpResponseModel
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RegisterOtpResponseModel</code>.
   * @alias module:model/RegisterOtpResponseModel
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>RegisterOtpResponseModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RegisterOtpResponseModel} obj Optional instance to populate.
   * @return {module:model/RegisterOtpResponseModel} The populated <code>RegisterOtpResponseModel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('responseCode'))
        obj.responseCode = ApiClient.convertToType(data['responseCode'], 'String');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('data'))
        obj.data = RegisterOtpResponseModelData.constructFromObject(data['data']);
    }
    return obj;
  }

  /**
   * @member {String} responseCode
   */
  exports.prototype.responseCode = undefined;

  /**
   * @member {String} message
   */
  exports.prototype.message = undefined;

  /**
   * @member {module:model/RegisterOtpResponseModelData} data
   */
  exports.prototype.data = undefined;


  return exports;

}));
