/*
 * SmartOTP SDK
 * SmartOTP API Specs for Payment
 *
 * OpenAPI spec version: 1.0.0
 * Contact: phuthinh@vnpt.vn
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.32
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SmartOtpSdk);
  }
}(this, function(expect, SmartOtpSdk) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('RegisterOtpRequestModel', function() {
      beforeEach(function() {
        instance = new SmartOtpSdk.RegisterOtpRequestModel();
      });

      it('should create an instance of RegisterOtpRequestModel', function() {
        // TODO: update the code to test RegisterOtpRequestModel
        expect(instance).to.be.a(SmartOtpSdk.RegisterOtpRequestModel);
      });

      it('should have the property activationCode (base name: "activationCode")', function() {
        // TODO: update the code to test the property activationCode
        expect(instance).to.have.property('activationCode');
        // expect(instance.activationCode).to.be(expectedValueLiteral);
      });

      it('should have the property transId (base name: "transId")', function() {
        // TODO: update the code to test the property transId
        expect(instance).to.have.property('transId');
        // expect(instance.transId).to.be(expectedValueLiteral);
      });

      it('should have the property pin (base name: "pin")', function() {
        // TODO: update the code to test the property pin
        expect(instance).to.have.property('pin');
        // expect(instance.pin).to.be(expectedValueLiteral);
      });

    });
  });

}));
